apiVersion: v2
name: oes
version: 3.12.6
appVersion: 3.12.4
description: "ISD-3.12.4 - Improvements in loading Application dashboard in ISD UI"
icon: https://raw.githubusercontent.com/OpsMx/enterprise-spinnaker/master/img/opsmx.png
maintainers:
- email: srinivas@opsmx.io
  name: ksrinimba
keywords:
  - OpsMx
  - OES
  - Autopilot
home: https://www.opsmx.com/
dependencies:
  - name: minio
    version: 8.0.9
    condition: global.minio.enabled
  - name: redis
    version: 10.5.3
    condition: installRedis
  - name: elasticsearch
    version: 7.5.0
    condition: enableCentralLogging
  - name: kibana
    version: 7.5.0
    condition: enableCentralLogging
  - name: fluent-bit
    version: 2.8.2
    condition: enableCentralLogging
  - name: prometheus
    version: 11.16.2
    condition: global.enableCentralMonitoring
  - name: gitea
    version: 5.0.1
    condition: global.gitea.enabled
